### ISSUE TITLE
Convexity of the Proposed Formulations

### ISSUE THREAD

**Issue by PranjalBiswas** [XiaojingGeorgeZhang/OBCA#2]
Hi

I went through the paper referenced in this repository. I am a bit confused w.r.t. the convexity of the proposed collision avoidance constraint formulations.  As of now I understand that assuming f(.,.), h(.,.) and l(.,.) are convex, then the formulations (10) and (15) are convex while formulations (13) and (18) are non-convex.  Is that correct? If it is, then I assume that I can solve formulations (10) and (15) using convex multistage solvers. Your opinion would be really helpful.

Kind Regards

Pranjal Biswas

**Comment by alexliniger** [comment]
The issue with convexity is that the obstacle avoidance constraint is not convex, thus, the original, as well as the new formulation, is non-convex. For example in (10) there is a bi-linearity, where p_k and lambda_k are multiplied, thus, even assuming that h and l are convex and f linear, would not result in a convex problem. 
In the paper, we use convexity of the distance function to reformulate the obstacle avoidance constraint using strong duality. This does not mean that the resulting constraint is convex, it only means that our reformulation is exact, since there is no duality gap. 
Best,
Alex

**Comment by PranjalBiswas** [comment]
Ok, then I will have to read more about the theory behind to understand the intricacies in that case, but does this non-convexity also contributes to comparatively high computation times in Table 2 for both the formulations, w.r.t. being able to implement it in real-time use cases?
